#!/usr/bin/env php
<?php

require './vendor/autoload.php';

use Brendt\Stitcher\Console;

// The console provides some helper commands while creating your website.
// Run ./stitcher in your terminal to see all options.
// See ./config.yml for more information.
$console = new Console();
$console->run();
