#!/usr/bin/env php
<?php

require './vendor/autoload.php';

use Brendt\Stitcher\App;

error_reporting(E_ALL ^ E_NOTICE);

// The console provides some helper commands while creating your website.
// Run ./stitcher in your terminal to see all options.
// See ./config.yml for more information.
$config = trim(@file_get_contents(__DIR__ . '/.env'));
App::init($config ? $config : './config/config.yml')::get('app.console')->run();
