/:
    template: blog/overview.twig
    variables:
        title: Blog
        overviewTitle: programming
        posts: src/content/blog.yaml
        meta:
            description: "A blog about modern PHP, the web, and programming in general. Follow my newsletter and YouTube channel as well."
    config:
        order:
            variable: posts
            field: date
            direction: desc

/screenshots:
    template: screenshots.twig
    variables:
        title: Screenshots
        content: src/content/screenshots.md

/books:
    template: books.twig
    variables:
        title: Books
        content: src/content/books.md

/blog/page-{page}:
    template: blog/overview.twig
    variables:
        title: Blog
        overviewTitle: programming
        posts: src/content/blog.yaml
        meta:
            description: "A blog about modern PHP, the web, and programming in general. Follow my newsletter and YouTube channel as well."
    config:
        pagination:
            variable: posts
            perPage: 100
            parameter: page
        order:
            variable: posts
            field: date
            direction: desc

/blog/{id}:
    template: blog/detail.twig
    variables:
        overviewTitle: programming
        post: src/content/blog.yaml
        meta:
            description: "A blog about modern PHP, the web, and programming in general. Follow my newsletter and YouTube channel as well."
    config:
        collection:
            variable: post
            parameter: id
        next: true
        meta: true

/blogs-for-devs/{id}:
    template: blog/detail.twig
    variables:
        overviewUrl: /blogs-for-devs/01-intro
        overviewTitle: Blog for Devs
        rssUrl: /blogs-for-devs/rss
        detailUrl: /blogs-for-devs
        post: src/content/blogs-for-devs.yaml
        meta:
            description: "A series on how to manage and grow your blog"
    config:
        collection:
            variable: post
            parameter: id
        next: true

/cookies:
    template: blog/detail.twig
    variables:
        post: src/content/cookies.yaml

/ads:
    template: blog/detail.twig
    variables:
        post: src/content/ads.yaml

/podcasts/all:
    template: blog/overview.twig
    variables:
        detailUrl: /podcasts
        rssUrl: /podcasts/rss
        overviewTitle: podcasts
        title: Podcasts
        posts: src/content/podcasts.yaml
        meta:
            description: "Podcast reviews — Listen. Critically."

/podcasts/{id}:
    template: blog/detail.twig
    variables:
        overviewUrl: /podcasts/all
        rssUrl: /podcasts/rss
        detailUrl: /podcasts
        post: src/content/podcasts.yaml
        meta:
            description: "Podcast reviews — Listen. Critically."
    config:
        collection:
            variable: post
            parameter: id
        next: true

/games/all:
    template: blog/overview.twig
    variables:
        detailUrl: /games
        rssUrl: /games/rss
        overviewTitle: games
        title: Games
        posts: src/content/games.yaml
        meta:
            description: "Anything game related crossing my path"

/games/{id}:
    template: blog/detail.twig
    variables:
        overviewUrl: /games/all
        rssUrl: /games/rss
        detailUrl: /games
        post: src/content/games.yaml
    config:
        collection:
            variable: post
            parameter: id
        next: true

/newsletter/success:
    template: newsletter/success.twig
    variables:
        title: Stitcher Mail
        meta:
            description: Subscribe to Stitcher Mail!

/newsletter/pending:
    template: newsletter/pending.twig
    variables:
        title: Stitcher Mail
        meta:
            description: Subscribe to Stitcher Mail!

/newsletter/unsub:
    template: newsletter/unsub.twig
    variables:
        title: Stitcher Mail
        meta:
            description: Subscribe to Stitcher Mail!

/newsletter/subscribe:
    template: newsletter/index.twig
    variables:
        title: Stitcher Mail
        meta:
            description: Subscribe to Stitcher Mail!

/php-74:
    template: blog/overview_tag.twig
    variables:
        title: PHP 7.4
        posts: src/content/blog.yaml
        intro: src/content/intro/php-74.md
        meta:
            description: "Short closures, typed properties, preloading and more"
    config:
        order:
            variable: posts
            field: date
            direction: desc
        filter:
            posts:
                tag: php-74

/favicon:
    template: favicon.twig


/mails-static:
    template: blog/overview.twig
    variables:
        title: Mails
        posts: src/content/mails-static.yaml
        detailUrl: '/mails-static'
    config:
        order:
            variable: posts
            field: date
            direction: desc

/mails-static/{id}:
    template: mails/static.twig
    variables:
        post: src/content/mails-static.yaml
    config:
        collection:
            variable: post
            parameter: id


/mails-road-81:
    template: blog/overview.twig
    variables:
        title: Mails
        posts: src/content/mails-road-81.yaml
        detailUrl: '/mails-road-81'
    config:
        order:
            variable: posts
            field: date
            direction: desc

/mails-road-81/{id}:
    template: mails/road-81.twig
    variables:
        post: src/content/mails-road-81.yaml
    config:
        collection:
            variable: post
            parameter: id


/mails-road-82:
    template: blog/overview.twig
    variables:
        title: Mails
        posts: src/content/mails-road-82.yaml
        detailUrl: '/mails-road-82'
    config:
        order:
            variable: posts
            field: date
            direction: desc

/mails-road-82/{id}:
    template: mails/road-82.twig
    variables:
        post: src/content/mails-road-82.yaml
    config:
        collection:
            variable: post
            parameter: id

/mails-stitcher/{id}:
    template: mails/stitcher.twig
    variables:
        post: src/content/mails-stitcher.yaml
    config:
        collection:
            variable: post
            parameter: id

/mails-front-line/{id}:
    template: mails/front-line.twig
    variables:
        post: src/content/mails-front-line.yaml
    config:
        collection:
            variable: post
            parameter: id

/de-job/success:
    template: de-job/success.twig
    variables:
        title: De Job
        meta:
            description: "De Job: een waargebeurde podcast"

/de-job/unsub:
    template: de-job/unsub.twig
    variables:
        title: De Job
        meta:
            description: "De Job: een waargebeurde podcast"

/de-job:
    template: de-job/index.twig
    variables:
        title: De Job
        meta:
            description: "De Job: een waargebeurde podcast"

/de-job/subscribe:
    template: de-job/index.twig
    variables:
        title: De Job
        meta:
            description: "De Job: een waargebeurde podcast"


/mails-de-job/{id}:
    template: mails/de-job.twig
    variables:
        post: src/content/mails-de-job.yaml
    config:
        collection:
            variable: post
            parameter: id

/sponsors:
    template: blog/detail.twig
    variables:
        post: src/content/sponsors.yaml

/novel/{id}:
    template: chapter.twig
    variables:
        title: Novel
        chapter: src/content/novel/novel.yaml
    config:
        collection:
            variable: chapter
            parameter: id

/novel:
    template: novel.twig
    variables:
        title: Novel
        chapters: src/content/novel/novel.yaml
        cover: /resources/img/novel/00-00.png

/one-day:
    template: novel.twig
    variables:
        title: One Day
        chapters: src/content/one-day/one-day.yaml

/present:
    template: slides.twig
    variables:
        title: Present
        slides: /src/content/present/slides.md

/timeline-taxi:
    template: taxi/index.twig

/timeline-taxi/pending:
    template: taxi/pending.twig

/timeline-taxi/success:
    template: taxi/success.twig

/timeline-taxi/unsub:
    template: taxi/unsub.twig
